//************************************************
//  RunFormula Expression Parser and Evaluator
//  Options include file
//  Rev. 31.03.2026

//  Author: Alexander Torubarov
//  Contact: runfla@yandex.com

//  Filename: runflaopt.inc

//  Copyright (C) 2026 Alexander Torubarov
//  Licensed under the MIT License.
//  See LICENSE file in the project root
//  or copy at https://opensource.org for full
//  license information.
//************************************************

// TODO -

// {$include runflamath.inc}


